[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unc"
version = "3.11.6"
requires-python = ">=3.8"

[project.optional-dependencies]
test = [
    "pytest",
    "uncertainties"
]

[tool.ruff]
select = ["E", "F", "W", "B", "I", "RUF", "UP"]
fix = true
