on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install pre-commit
      - run: pre-commit install
      - run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.12]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install package
        run: pip install nox

      - name: Test package
        run: nox -s tests
